apiVersion: v1
kind: Namespace
metadata:
  name: infra
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: infra
spec:
  loggingRef: infra
  controlNamespace: infra
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: FluentbitAgent
metadata:
  name: infra
spec:
  loggingRef: infra
  positiondb:
    hostPath:
      path: ""
  bufferStorageVolume:
    hostPath:
      path: ""
  network:
    connectTimeout: 2
  targetLoggings:
    - loggingName: a
      namespaces:
        - a
    - loggingName: b
      namespaces:
        - b1
        - b2
