apiVersion: v1
kind: Namespace
metadata:
  name: a-control
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: a
spec:
  loggingRef: a
  fluentd:
    fluentLogDestination: stdout
    fluentOutLogrotate:
      enabled: false
  controlNamespace: a-control
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: http
  namespace: a-control
spec:
  loggingRef: a
  http:
    endpoint: http://test-receiver.infra:8080/tenant-a
    content_type: application/json
    buffer:
      type: memory
      timekey: 1s
      timekey_wait: 0s
