apiVersion: v1
kind: Namespace
metadata:
  name: infra
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: infra
spec:
  loggingRef: infra
  fluentd: {}
  controlNamespace: infra
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: FluentbitAgent
metadata:
  name: infra
spec:
  loggingRef: infra
  inputTail:
    storage.type: filesystem
  forwardOptions:
    Workers: 0
  syslogng_output:
    Workers: 0
  positiondb:
    hostPath:
      path: ""
  bufferStorageVolume:
    hostPath:
      path: ""
  network:
    connectTimeout: 2
  logRouting:
    enabled: true
    targets:
    - logging: infra
      allNamespaces: true
    - logging: a
    - logging: b
    - logging: c
